# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      sudo docker-up
    init: docker-compose up --no-start
    command: docker-compose up
